BigQuery Connector Actions and Locators changes
cdapio/cdap-e2e-tests pull request #43
Opened 2021-11-17 12:50 UTC by Ragini2

This PR needs to be reviewed by internal Cloudsufi Team only.

2021-11-24 05:07 UTC, sumitnigamcs requested changes

2021-11-24 05:07 UTC, sumitnigamcs commented on src/main/java/io/cdap/e2e/pages/actions/CdfBQActions.java
> +  private static BigQueryLocators cdfBigQueryLocators;
why is this declared when not used

2021-11-24 05:07 UTC, sumitnigamcs commented on src/main/java/io/cdap/e2e/pages/actions/CdfBQActions.java
> +  public static BigQueryLocators bigQueryLocators = null;
global variables have default values, so initialization not required.

2021-11-24 05:07 UTC, sumitnigamcs commented on src/main/java/io/cdap/e2e/pages/actions/CdfBQActions.java
> +    SeleniumHelper.waitElementIsVisible(BigQueryLocators.closeButton, 200);
is this wait time really needed? Please cross check from CdfGcsAction.closeButton(), it doesn't have any wait time

2021-11-24 05:07 UTC, sumitnigamcs commented on src/main/java/io/cdap/e2e/pages/actions/CdfBQActions.java
> +    SeleniumHelper.waitElementIsVisible(BigQueryLocators.useconnection, 100);
100 sec is quite a long time to wait, you may use ConstantsUtil.ONE variable here

2021-11-24 05:07 UTC, sumitnigamcs commented on src/main/java/io/cdap/e2e/pages/actions/CdfGcsActions.java
> +    SeleniumHelper.waitElementIsVisible(CdfGCSLocators.closeButton, 200L);
take care of this wait time, as mentioned in above comment

2021-11-24 05:07 UTC, sumitnigamcs commented on src/main/java/io/cdap/e2e/pages/actions/CdfStudioActions.java
> +    SeleniumHelper.waitElementIsVisible(CdfStudioLocators.previewSuccessbanner, 400);
too long wait time, call the other overloaded method, without second param

2021-11-24 05:07 UTC, sumitnigamcs commented on src/main/java/io/cdap/e2e/pages/actions/CdfStudioActions.java
>    }
you are modifying the existing code here, which is never suggested.

2021-11-24 05:07 UTC, sumitnigamcs commented on src/main/java/io/cdap/e2e/pages/actions/CdfStudioActions.java
> +    SeleniumHelper.waitElementIsVisible(CdfStudioLocators.previewSuccessbanner, 400);
too long a wait time

2021-11-24 05:07 UTC, sumitnigamcs commented on src/main/java/io/cdap/e2e/pages/actions/CdfStudioActions.java
> +    SeleniumHelper.waitElementIsVisible(BigQueryLocators.previewData, 10);
too long wait time

2021-11-24 05:07 UTC, sumitnigamcs commented on src/main/java/io/cdap/e2e/pages/locators/BigQueryLocators.java
> +  public static WebElement useconnection;
make all the variable names camelcase useconnection -> useConnection.
Use alt+shift+R for renaming, so that all the usages are modified accordingly

2021-11-24 05:07 UTC, sumitnigamcs commented on src/main/java/io/cdap/e2e/pages/locators/CdfBigQueryPropertiesLocators.java
> +  public static WebElement bigQuerysourceTable;
take care of camelcasing

2021-11-24 05:07 UTC, sumitnigamcs commented on src/main/java/io/cdap/e2e/pages/locators/CdfGCSLocators.java
>    public static WebElement referenceName;
you are modifying the locator which was being used earlier while entering GCS properties, changing it might impact the existing code adversely. Is this change well thought ?

2021-11-24 05:07 UTC, sumitnigamcs commented on src/main/java/io/cdap/e2e/pages/locators/CdfStudioLocators.java
> +  public static WebElement gCS;
gCS ->gcs

2021-11-24 05:07 UTC, sumitnigamcs commented on src/main/java/io/cdap/e2e/pages/locators/CdfStudioLocators.java
> +  public static WebElement gCSProperties;
gCSProperties  -> gcsProperties

2021-11-24 05:07 UTC, sumitnigamcs commented on src/main/java/io/cdap/e2e/pages/locators/CdfStudioLocators.java
> +  public static WebElement previewSuccessbanner;
check all camelcasing of this file

2021-11-24 05:07 UTC, sumitnigamcs commented on src/main/resources/connectionParameters.properties
> +jsondata=
?

2021-11-24 05:07 UTC, sumitnigamcs commented on src/main/java/io/cdap/e2e/pages/actions/CdfStudioActions.java
> +    SeleniumHelper.waitAndClick(element);
make it like this: SeleniumHelper.waitAndClick(CdfStudioLocators.bqBucket)

2021-11-24 05:07 UTC, sumitnigamcs commented on src/main/java/io/cdap/e2e/pages/actions/CdfBigQueryPropertiesActions.java
> +    CdfBQActions.enterPartition_start_Date();
this looks like a compilation issue to me, this method accepts a parameter. Same for enterpartition_end_date

2021-11-24 05:07 UTC, sumitnigamcs commented on src/main/java/io/cdap/e2e/pages/actions/CdfBigQueryPropertiesActions.java
> +    CdfBQActions.getSchema();
you might need to wait for visibility of schemabutton, before clicking on validate button. Verify this, i might be wrong

2021-11-24 05:07 UTC, sumitnigamcs commented on src/main/resources/connectionParameters.properties
> +
where are all these properties used?

2021-11-24 11:50 UTC, Ragini2 commented on src/main/java/io/cdap/e2e/pages/actions/CdfBQActions.java
> +  public static BigQueryLocators bigQueryLocators = null;
Removed null value

2021-11-24 11:51 UTC, Ragini2 commented on src/main/java/io/cdap/e2e/pages/actions/CdfBQActions.java
> +    SeleniumHelper.waitElementIsVisible(BigQueryLocators.useconnection, 100);
Removed wait seconds

2021-11-24 11:52 UTC, Ragini2 commented on src/main/java/io/cdap/e2e/pages/actions/CdfGcsActions.java
> +    SeleniumHelper.waitElementIsVisible(CdfGCSLocators.closeButton, 200L);
Removed wait seconds

2021-11-24 11:52 UTC, Ragini2 commented on src/main/java/io/cdap/e2e/pages/actions/CdfStudioActions.java
>    }
Working as expected

2021-11-24 11:53 UTC, Ragini2 commented on src/main/java/io/cdap/e2e/pages/actions/CdfStudioActions.java
> +    SeleniumHelper.waitElementIsVisible(BigQueryLocators.previewData, 10);
removed wait seconds

2021-11-24 11:53 UTC, Ragini2 commented on src/main/java/io/cdap/e2e/pages/locators/BigQueryLocators.java
> +  public static WebElement useconnection;
changed to useConnection

2021-11-24 11:54 UTC, Ragini2 commented on src/main/java/io/cdap/e2e/pages/locators/CdfBigQueryPropertiesLocators.java
> +  public static WebElement bigQuerysourceTable;
changed to bigquerySourcetable

2021-11-24 11:54 UTC, Ragini2 commented on src/main/java/io/cdap/e2e/pages/locators/CdfStudioLocators.java
> +  public static WebElement gCS;
changed to gcs

2021-11-24 11:55 UTC, Ragini2 commented on src/main/java/io/cdap/e2e/pages/locators/CdfStudioLocators.java
> +  public static WebElement gCSProperties;
changed to gcsProperties

2021-11-24 11:56 UTC, Ragini2 commented on src/main/resources/connectionParameters.properties
> +jsondata=
added in google clod project

2021-11-24 11:57 UTC, Ragini2 commented on src/main/java/io/cdap/e2e/pages/actions/CdfStudioActions.java
> +    SeleniumHelper.waitAndClick(element);
changed as above

2021-11-24 11:57 UTC, Ragini2 commented on src/main/java/io/cdap/e2e/pages/actions/CdfBigQueryPropertiesActions.java
> +    CdfBQActions.enterPartition_start_Date();
cahnged

2021-11-24 11:57 UTC, Ragini2 commented on src/main/java/io/cdap/e2e/pages/actions/CdfBigQueryPropertiesActions.java
> +    CdfBQActions.getSchema();
changed

2021-11-24 11:57 UTC, Ragini2 commented on src/main/resources/connectionParameters.properties
> +
removed from e2e properties file

2021-11-30 08:22 UTC, sumitnigamcs requested changes

2021-11-30 08:22 UTC, sumitnigamcs commented on src/main/java/io/cdap/e2e/pages/actions/CdfBQActions.java
> +    SeleniumHelper.replaceElementValue(BigQueryLocators.filTer, filter);
why this change?

2021-11-30 08:22 UTC, sumitnigamcs commented on src/main/java/io/cdap/e2e/pages/actions/CdfBigQueryPropertiesActions.java
> +  public static void clickBigqueryProperties() {
clickBigqueryProperties -> clickBigQueryProperties

2021-11-30 08:22 UTC, sumitnigamcs commented on src/main/java/io/cdap/e2e/pages/locators/CdfBigQueryPropertiesLocators.java
> +  public static WebElement datasetProjectID;
datasetProjectID -> datasetProjectId

2021-11-30 08:22 UTC, sumitnigamcs commented on src/main/java/io/cdap/e2e/pages/actions/CdfBigQueryPropertiesActions.java
> +  public static void enterBigqueryDataSet(String dataSet) {
enterBigqueryDataSet -> enterBigQueryDataset
dataSet -> dataset

2021-11-30 10:47 UTC, sumitnigamcs commented on src/main/java/io/cdap/e2e/pages/locators/CdfStudioLocators.java
>  }
file doesnt end with new line.
verify checkstyle file has been included in intellij. 
Checkstyle settings can be downloaded from https://cdap.atlassian.net/wiki/spaces/CE/pages/1594098619/Coding+Standard

2021-12-06 07:33 UTC, closed without merging